artifacts_root : artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: https://github.com/markandey1414/images/raw/main/Chicken-fecal-images.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion